### ISSUE TITLE
Ошибка в helpers.Order

### ISSUE THREAD

**Issue by TigenTigen** [fogstream/fs-pochta-api#7]
Здравствуйте, столкнулась с пробемой при применении метода helpers.Order.add_items().

`   
def add_items(self, items: List[Item]) -> None:
        """
        Добавление товарных вложений РПО.

        :param items: Список вложений
        """
        if not items:
            self.items = items
        else:
            self.items.extend(items)
`
В то же время в __init__.py: `self.items = None`

Таким обрзам, вызывая метод add_items с ненулевым списком вызовет:

` File "/root/.cache/pypoetry/virtualenvs/server-slTVhXXG-py3.7/lib/python3.7/site-packages/pochta/helpers.py", line 432, in add_items
    self.items.extend(items)
AttributeError: 'NoneType' object has no attribute 'extend'
`

Необходимо заменить базовое значение items на пустой список.

**Comment by fadedDexofan** [comment]
Привет! Спасибо за репорт. Поправил.
